# Generated by Django 4.1.4 on 2022-12-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsDSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='краткое имя')),
                ('long_name', models.CharField(max_length=250, verbose_name='официальное имя')),
                ('operation_date', models.DateTimeField(verbose_name='дата начала эксплуатации')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Объект, подразделение',
                'verbose_name_plural': 'Объекты, подразделения',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=10, verbose_name='КПП')),
            ],
            options={
                'verbose_name': 'Реквизиты подразделения',
                'verbose_name_plural': 'Список реквизитов подразделений (объектов)',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='день недели')),
                ('start_time', models.CharField(max_length=5, verbose_name='Начало дня')),
                ('end_time', models.CharField(max_length=5, verbose_name='Конец дня')),
                ('day_type', models.CharField(choices=[('weekday', 'Рабочий день'), ('holiday', 'Выходной')], max_length=255, verbose_name='Рабочий или выходной')),
            ],
        ),
    ]
