# Generated by Django 4.1.4 on 2022-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0002_asfold_basecategory_imagemedia_pageold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategory',
            name='newname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='новое название'),
        ),
    ]
