# Generated by Django 4.1.4 on 2022-12-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0003_basecategory_newname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='краткое имя')),
                ('long_name', models.CharField(max_length=250, verbose_name='официальное имя')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('contacts', models.CharField(max_length=200, verbose_name='контакты')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название услуги')),
                ('descriprion', models.CharField(max_length=100, verbose_name='краткое описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.DeleteModel(
            name='ASFOld',
        ),
        migrations.DeleteModel(
            name='ImageMedia',
        ),
        migrations.DeleteModel(
            name='ObjectsDSS',
        ),
        migrations.DeleteModel(
            name='PageOld',
        ),
        migrations.DeleteModel(
            name='Requisites',
        ),
        migrations.AlterModelOptions(
            name='basecategory',
            options={'verbose_name': 'Категория (пункт меню)', 'verbose_name_plural': 'Категории (пункты меню)'},
        ),
    ]
