# Generated by Django 4.1.4 on 2022-12-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0004_object_service_delete_asfold_delete_imagemedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descriprion',
            field=models.TextField(max_length=100, verbose_name='краткое описание'),
        ),
    ]
