# Generated by Django 4.1.4 on 2022-12-28 03:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0005_alter_service_descriprion'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.basecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='descriprion',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=60, verbose_name='название услуги'),
        ),
    ]
