# Generated by Django 4.1.4 on 2022-12-28 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0006_object_category_alter_service_descriprion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='service',
            field=models.ManyToManyField(help_text='выберите доступные спортивные услуги', to='sportdss.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.basecategory'),
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='title',
            field=models.CharField(max_length=25, verbose_name='старое название'),
        ),
    ]
