# Generated by Django 4.1.4 on 2022-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0008_managment'),
    ]

    operations = [
        migrations.AddField(
            model_name='managment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
