# Generated by Django 4.1.4 on 2022-12-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0009_managment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='managment',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.object'),
        ),
    ]
