# Generated by Django 4.1.4 on 2022-12-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0012_alter_about_options_managment_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managment',
            name='category',
        ),
    ]
