# Generated by Django 4.1.4 on 2022-12-28 09:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0013_remove_managment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название контакта')),
                ('description', models.TextField(max_length=60, verbose_name='описание контакта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.RenameField(
            model_name='about',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.CreateModel(
            name='WorkingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor_uploader.fields.RichTextUploadingField(max_length=160, verbose_name='режим работы')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'режим работы',
                'verbose_name_plural': 'режимы работ',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='телефонный номер')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=60, verbose_name='электронный адрес')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'электронный адрес',
                'verbose_name_plural': 'электронные адреса',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.about', verbose_name='"о нас"'),
        ),
    ]
