# Generated by Django 4.1.4 on 2022-12-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0017_contact_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=35, verbose_name='название контакта'),
        ),
    ]
