# Generated by Django 4.1.4 on 2022-12-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0018_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=100, verbose_name='описание контакта'),
        ),
    ]
