# Generated by Django 4.1.4 on 2022-12-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0019_alter_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='managment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.contact', verbose_name='Контакты'),
        ),
    ]
