# Generated by Django 4.1.4 on 2023-01-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportdss', '0021_alter_contact_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(blank=True, choices=[('status', 'уставные документы'), ('tarif', 'расценки'), ('contract', 'договор'), ('cert', 'сертификаты'), ('rules', 'правила'), ('reports', 'отчеты'), ('purchase', 'закупки'), ('work', 'охрана труда'), ('tax', 'налоговый вычет')], default='reports', help_text='выберите тип документа', max_length=10, verbose_name='тип документа')),
                ('url', models.URLField(verbose_name='ссылка на яндекс диск')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.RenameField(
            model_name='object',
            old_name='long_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='basecategory',
            name='slug',
            field=models.CharField(blank=True, help_text='краткое название пути в url', max_length=15, null=True, verbose_name='Слуг для url'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='about',
            field=models.ForeignKey(blank=True, help_text='не выбирать если не надо отображать в пункте меню "о нас - контакты"', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sportdss.about', verbose_name='"о нас"'),
        ),
    ]
