# Generated by Django 4.1.4 on 2022-12-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название языка', max_length=100, verbose_name='название языка')),
            ],
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': [], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'verbose_name': 'Экземпляр в библиотеке', 'verbose_name_plural': 'Экземпляры в библиотеке'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='имя данное при рождении', max_length=100, verbose_name='Имя (алам)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='имя семейное (фамилия или ряд ибн для арабоговорящих) ', max_length=100, verbose_name='Фамилия (насаб)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, help_text='религиозное имя или титул, прозвище, достижение для арабоговорящих', max_length=100, verbose_name='Второе имя (среднее, прозвище, псевдоним))'),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, help_text='склоняемое имя отца для восточнославянских народов, не склоняемое имя отца для тюркоговорящих народов или место рождения, религиозная принадлежность для арабоговорящих', max_length=100, verbose_name='Отчество (нисба)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='style_name',
            field=models.CharField(blank=True, choices=[('lt', 'латинский'), ('ru', 'славянский'), ('ch', 'азиатско-китайский'), ('ar', 'арабский'), ('tr', 'тюрко и монгольский')], default='ru', help_text='выберите стиль написания полного имени автора', max_length=2, verbose_name='стиль написания имени'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='выберите язык на котором написана книга', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
    ]
